/*
 * This file is generated by jOOQ.
 */
package com.arijit.restaurant.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID orderId;
    private UUID menuId;

    public OrderItems() {}

    public OrderItems(OrderItems value) {
        this.orderId = value.orderId;
        this.menuId = value.menuId;
    }

    @ConstructorProperties({ "orderId", "menuId" })
    public OrderItems(
        UUID orderId,
        UUID menuId
    ) {
        this.orderId = orderId;
        this.menuId = menuId;
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public UUID getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public OrderItems setOrderId(UUID orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.order_items.menu_id</code>.
     */
    public UUID getMenuId() {
        return this.menuId;
    }

    /**
     * Setter for <code>public.order_items.menu_id</code>.
     */
    public OrderItems setMenuId(UUID menuId) {
        this.menuId = menuId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderItems other = (OrderItems) obj;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.menuId == null) {
            if (other.menuId != null)
                return false;
        }
        else if (!this.menuId.equals(other.menuId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.menuId == null) ? 0 : this.menuId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderItems (");

        sb.append(orderId);
        sb.append(", ").append(menuId);

        sb.append(")");
        return sb.toString();
    }
}
