/*
 * This file is generated by jOOQ.
 */
package com.arijit.restaurant;


import com.arijit.restaurant.tables.Menu;
import com.arijit.restaurant.tables.OrderItems;
import com.arijit.restaurant.tables.Orders;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.menu</code>.
     */
    public static final Menu MENU = Menu.MENU;

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;
}
