/*
 * This file is generated by jOOQ.
 */
package com.arijit.restaurant.tables.records;


import com.arijit.restaurant.tables.Menu;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuRecord extends TableRecordImpl<MenuRecord> implements Record8<UUID, String, String, Double, String, LocalDateTime, LocalDateTime, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.menu.id</code>.
     */
    public MenuRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.menu.item_name</code>.
     */
    public MenuRecord setItemName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.item_name</code>.
     */
    public String getItemName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.menu.status</code>.
     */
    public MenuRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.menu.price</code>.
     */
    public MenuRecord setPrice(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.menu.description</code>.
     */
    public MenuRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.menu.created_at</code>.
     */
    public MenuRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.menu.updated_at</code>.
     */
    public MenuRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.menu.restaurant_id</code>.
     */
    public MenuRecord setRestaurantId(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.menu.restaurant_id</code>.
     */
    public UUID getRestaurantId() {
        return (UUID) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, Double, String, LocalDateTime, LocalDateTime, UUID> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, Double, String, LocalDateTime, LocalDateTime, UUID> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Menu.MENU.ID;
    }

    @Override
    public Field<String> field2() {
        return Menu.MENU.ITEM_NAME;
    }

    @Override
    public Field<String> field3() {
        return Menu.MENU.STATUS;
    }

    @Override
    public Field<Double> field4() {
        return Menu.MENU.PRICE;
    }

    @Override
    public Field<String> field5() {
        return Menu.MENU.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Menu.MENU.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Menu.MENU.UPDATED_AT;
    }

    @Override
    public Field<UUID> field8() {
        return Menu.MENU.RESTAURANT_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getItemName();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public Double component4() {
        return getPrice();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public UUID component8() {
        return getRestaurantId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getItemName();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public Double value4() {
        return getPrice();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public UUID value8() {
        return getRestaurantId();
    }

    @Override
    public MenuRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public MenuRecord value2(String value) {
        setItemName(value);
        return this;
    }

    @Override
    public MenuRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public MenuRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public MenuRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public MenuRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MenuRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MenuRecord value8(UUID value) {
        setRestaurantId(value);
        return this;
    }

    @Override
    public MenuRecord values(UUID value1, String value2, String value3, Double value4, String value5, LocalDateTime value6, LocalDateTime value7, UUID value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MenuRecord
     */
    public MenuRecord() {
        super(Menu.MENU);
    }

    /**
     * Create a detached, initialised MenuRecord
     */
    @ConstructorProperties({ "id", "itemName", "status", "price", "description", "createdAt", "updatedAt", "restaurantId" })
    public MenuRecord(UUID id, String itemName, String status, Double price, String description, LocalDateTime createdAt, LocalDateTime updatedAt, UUID restaurantId) {
        super(Menu.MENU);

        setId(id);
        setItemName(itemName);
        setStatus(status);
        setPrice(price);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setRestaurantId(restaurantId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MenuRecord
     */
    public MenuRecord(com.arijit.restaurant.tables.pojos.Menu value) {
        super(Menu.MENU);

        if (value != null) {
            setId(value.getId());
            setItemName(value.getItemName());
            setStatus(value.getStatus());
            setPrice(value.getPrice());
            setDescription(value.getDescription());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setRestaurantId(value.getRestaurantId());
            resetChangedOnNotNull();
        }
    }
}
